apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
spec:
  template:
    spec:
      containers:
      - name: shipping-service
        env:
        - name: OTEL_SERVICE_NAME
          value: "shipping-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_JAVAAGENT_DEBUG
          value: "true"
