resources:
  - ../../base
  - prometheus.yaml
  - prometheus-rbac.yaml

images:
  - name: order-service
    newTag: v0.3-metrics
  - name: shipping-service
    newTag: v0.3-metrics
  - name: inventory-service
    newTag: v0.3-metrics

patches:
  - path: grafana-datasource-patch.yaml
    target:
      kind: ConfigMap
      name: grafana-datasources
