apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.8.4
          ports:
            - containerPort: 3100
              name: http-metrics
              protocol: TCP
          command:
            - /usr/bin/loki
          args:
            - -config.file=/etc/loki/local-config.yaml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/loki
            - name: data
              mountPath: /tmp/loki
          securityContext:
            runAsUser: 10001
            runAsGroup: 10001
          resources:
            limits:
              cpu: "1000m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
  selector:
    app: loki
